# Generated by Django 5.0.6 on 2024-05-22 09:46

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="tallImage",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="default_tall.jpg",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[1618, 2878],
                upload_to="tallimages",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="squareImage",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="default_square.jpg",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[1000, 1000],
                upload_to="squareimages",
            ),
        ),
    ]
