# Generated by Django 5.0.6 on 2024-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_image_tallimage_alter_image_squareimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="date_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
