# Generated by Django 5.0.6 on 2024-05-24 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_category_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="date_created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
